name = "bookscan-worker"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "bookscan"
database_id = "5aa2cac9-de03-4ac0-a3b0-f51c9fe1c272"
migrations_dir = "migrations"

[observability.logs]
enabled = true
invocation_logs = true

[vars]
CORS_ORIGIN = "https://bookscan.pages.dev"
